# Generated by Django 5.0.3 on 2024-04-29 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('file', models.FileField(max_length=256, upload_to='files/design/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='Имя пользователя')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('surname', models.CharField(max_length=256, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('role', models.IntegerField(blank=True, verbose_name='Роль')),
                ('date_of_register', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('date_of_change', models.DateTimeField(auto_now=True, verbose_name='Дата изменении')),
                ('ban_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала блокировки')),
                ('ban_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата конца блокировки')),
                ('subscribe', models.BooleanField(blank=True, default=0, verbose_name='Подписка')),
                ('is_custom_user', models.BooleanField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('design_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudapp.design', verbose_name='Дизайн')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Архив', max_length=128, verbose_name='Название')),
                ('color', models.CharField(blank=True, default='ffffff', max_length=8, verbose_name='Цвет')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('image', models.ImageField(upload_to='users_images/%Y/%m/%d/')),
                ('file_size', models.IntegerField(verbose_name='Размер изображения')),
                ('format', models.CharField(max_length=6, verbose_name='Формат изображения')),
                ('width', models.IntegerField(blank=True, verbose_name='Ширина')),
                ('height', models.IntegerField(blank=True, verbose_name='Высота')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('archive_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudapp.archive', verbose_name='Архив')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
