# Generated by Django 5.0.3 on 2024-04-29 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapp', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='design_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cloudapp.design', verbose_name='Дизайн'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=256, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscribe',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.CharField(max_length=256, null=True, verbose_name='Имя'),
        ),
    ]
