# Generated by Django 5.0.3 on 2024-05-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapp', '0005_alter_image_archive_id_alter_image_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='format',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Формат изображения'),
        ),
    ]
