# Generated by Django 5.0.3 on 2024-05-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapp', '0006_alter_image_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='archive_id',
        ),
        migrations.AddField(
            model_name='archive',
            name='images',
            field=models.ManyToManyField(to='cloudapp.image', verbose_name='Изображения'),
        ),
    ]
