# Generated by Django 5.0.3 on 2024-05-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapp', '0008_alter_archive_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='images',
            field=models.ManyToManyField(to='cloudapp.image', verbose_name='Изображения'),
        ),
    ]
